services:
  - type: web
    name: nexus-backend
    env: python
    runtime: python
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir backend app:app

